export const informationAboutAllBooks = [
    {
        coverImageUrl: './assets/img/Зов ночной птицы.jpg',
        title: 'Зов ночной птицы',
        author: {
            firstName: 'Роберт',
            middleName: 'Рик',
            lastName: 'Маккаммон',
        },
        rating: 10,
        yearOfReading: 2024,
        pathBookUrl: './assets/book/Зов ночной птицы.fb2',
        bookSequence: {
            sequenceName: 'Мэтью Корбетт',
            positionInSequence: 1,
        },
        genres: ['Детектив', 'Триллер'],
        rereadIn: [2024],
        quotes: '',
        notes: '',
    },
    {
        coverImageUrl: './assets/img/Зов ночной птицы.jpg',
        title: 'Зов ночной птицы',
        author: {
            firstName: 'Роберт',
            middleName: 'Рик',
            lastName: 'Маккаммон',
        },
        rating: 9,
        yearOfReading: 2021,
        pathBookUrl: './assets/book/Зов ночной птицы.fb2',
        bookSequence: {
            sequenceName: 'Мэтью Корбетт',
            positionInSequence: 1,
        },
        genres: ['Детектив', 'Триллер'],
        rereadIn: [2024],
        quotes: '',
        notes: '',
    },
    {
        coverImageUrl: './assets/img/Зов ночной птицы.jpg',
        title: 'Зов ночной птицы',
        author: {
            firstName: 'Роберт',
            middleName: 'Рик',
            lastName: 'Маккаммон',
        },
        rating: 8,
        yearOfReading: 2023,
        pathBookUrl: './assets/book/Зов ночной птицы.fb2',
        bookSequence: {
            sequenceName: 'Мэтью Корбетт',
            positionInSequence: 1,
        },
        genres: ['Детектив', 'Триллер'],
        rereadIn: [2024],
        quotes: '',
        notes: '',
    },
    {
        coverImageUrl: './assets/img/Зов ночной птицы.jpg',
        title: 'Зов ночной птицы',
        author: {
            firstName: 'Роберт',
            middleName: 'Рик',
            lastName: 'Маккаммон',
        },
        rating: 9,
        yearOfReading: 2020,
        pathBookUrl: './assets/book/Зов ночной птицы.fb2',
        bookSequence: {
            sequenceName: 'Мэтью Корбетт',
            positionInSequence: 1,
        },
        genres: ['Детектив', 'Триллер'],
        rereadIn: [2024],
        quotes: '',
        notes: '',
    },
    {
        coverImageUrl: './assets/img/Зов ночной птицы.jpg',
        title: 'Зов ночной птицы',
        author: {
            firstName: 'Роберт',
            middleName: 'Рик',
            lastName: 'Маккаммон',
        },
        rating: 7,
        yearOfReading: 2022,
        pathBookUrl: './assets/book/Зов ночной птицы.fb2',
        bookSequence: {
            sequenceName: 'Мэтью Корбетт',
            positionInSequence: 1,
        },
        genres: ['Детектив', 'Триллер'],
        rereadIn: [2024],
        quotes: '',
        notes: '',
    },
    {
        coverImageUrl: './assets/img/Зов ночной птицы.jpg',
        title: 'Зов ночной птицы',
        author: {
            firstName: 'Роберт',
            middleName: 'Рик',
            lastName: 'Маккаммон',
        },
        rating: 10,
        yearOfReading: 2021,
        pathBookUrl: './assets/book/Зов ночной птицы.fb2',
        bookSequence: {
            sequenceName: 'Мэтью Корбетт',
            positionInSequence: 1,
        },
        genres: ['Детектив', 'Триллер'],
        rereadIn: [2024],
        quotes: '',
        notes: '',
    },
    {
        coverImageUrl: './assets/img/Зов ночной птицы.jpg',
        title: 'Зов ночной птицы',
        author: {
            firstName: 'Роберт',
            middleName: 'Рик',
            lastName: 'Маккаммон',
        },
        rating: 8,
        yearOfReading: 2021,
        pathBookUrl: './assets/book/Зов ночной птицы.fb2',
        bookSequence: {
            sequenceName: 'Мэтью Корбетт',
            positionInSequence: 1,
        },
        genres: ['Детектив', 'Триллер'],
        rereadIn: [2024],
        quotes: '',
        notes: '',
    },
    {
        coverImageUrl: './assets/img/Зов ночной птицы.jpg',
        title: 'Зов ночной птицы',
        author: {
            firstName: 'Роберт',
            middleName: 'Рик',
            lastName: 'Маккаммон',
        },
        rating: 9,
        yearOfReading: 2023,
        pathBookUrl: './assets/book/Зов ночной птицы.fb2',
        bookSequence: {
            sequenceName: 'Мэтью Корбетт',
            positionInSequence: 1,
        },
        genres: ['Детектив', 'Триллер'],
        rereadIn: [2024],
        quotes: '',
        notes: '',
    },
]